---
sidebar: sidebar 
permalink: reference-get-started-snapcenter-service.html 
keywords: snapcenter service, getting started, connector, HDBSQL client, SAP HANA systems, protect SAP HANA systems 
summary: SnapCenter サービスを導入してデータを保護するためのタスク。 
---
= はじめに
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter サービスを利用して、データを保護する手順をいくつか紹介します。

[role="quick-margin-para"]
お勧めします https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-signing-up.html["NetApp Cloud Central に登録"^]、 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["Cloud Manager にログインします"^]をクリックし、を設定します https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-setting-up-netapp-accounts.html["ネットアップアカウント"^]。

[role="quick-margin-para"]
SnapCenter サービスを導入できるのは、アカウント管理者だけです。ただし、アカウント管理者と SnapCenter 管理者は、どちらもさまざまな操作を実行できます。 https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-user-roles.html["詳細はこちら。"^]

[role="quick-margin-para"]
すべてのを確認してください link:prerequisites-azure-connector-snapcenter-service.html["前提条件"] コネクタを作成して SnapCenter サービスを有効にするには、次の手順を実行します。

[role="quick-margin-para"]
お勧めします link:create-azure-connector-user-consent-snapcenter-service.html["Azure for SnapCenter サービスでコネクタを作成します"]。

[role="quick-margin-para"]
前提条件をすべて満たすコネクタがある場合は、そのコネクタを使用できます。

[role="quick-margin-para"]
Cloud Manager で Azure NetApp Files 作業環境を作成し、ネットアップアカウント、容量プール、ボリューム、 Snapshot を作成および管理します。 https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/task-manage-anf.html["詳細はこちら。"^]

[role="quick-margin-para"]
お勧めします link:enable-snapcenter-service-azure-netapp-files.html["SnapCenter サービスを有効にします"] Cloud Manager UI を使用SnapCenter サービスが有効になると、 SnapCenter サービスをホストする Azure Kubernetes Service （ AKS ）クラスタが作成されます。

[role="quick-margin-para"]
お勧めします link:install-hdbsql-client-snapcenter-service.html["HDBSQL クライアントをインストールします"] をクリックして、 SAP HANA データベースに対してデータ保護処理を実行します。HDBSQL クライアントは、 SAP HANA システムとの通信に使用されます。

[role="quick-margin-para"]
手動で行う必要があります link:add-sap-hana-systems-non-data-volumes-snapcenter-service.html["SAP HANA システムを追加します"]。

[role="quick-margin-para"]
そのあとで、を実行できます link:create-backup-ondemand-policies-schedule-sap-hana.html["SAP HANA システムをバックアップ"] システム定義またはカスタムのポリシーを使用する。データ損失が発生した場合は、を実行できます link:restore-sap-hana-systems.html["SAP HANA システムをリストア"] そのシステムのバックアップを使用する。
