---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes' 
summary: SnapCenter サービスの新機能について説明します。 
---
= SnapCenter サービスの新機能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter サービスの新機能について説明します。



== 2021 年 12 月 21 日



=== Apache log4j の脆弱性に対する修正

SnapCenter サービス 1.0.1 をアップグレードすると、バージョン 2.9.1 から 2.17 に Apache log4j がアップグレードされ、次の脆弱性が解決されます： CVE-20244228 、 CVE-2012-4104 、および CVE-2016-45105 。

SnapCenter サービスクラスタは最新バージョンに自動更新される必要があります。SnapCenter サービス UI に、クラスタが 1.0.1.1251 以降であることを確認する必要があります。



== 2021 年 10 月 13 日



=== SnapCenter サービス 1.0.0 のサポート

* SnapCenter サービスは、ネットアップクラウドストレージで実行されているアプリケーションにデータ保護機能を提供します。NetApp Cloud Manager で SnapCenter サービスを有効にすると、 Azure NetApp Files （ ANF ）上にある SAP HANA ® システムを、アプリケーションと整合性のある効率的なポリシーベースのバックアップとリストアで利用できます。
+
link:concept-overview-architecture-limitation-functionalities-snapcenter-service.html["SnapCenter サービスについて"]

* コネクタを作成し、 SnapCenter サービスを有効にして、 SAP HANA システムを追加し、バックアップとリストアの処理を実行する必要があります。
+
link:reference-get-started-snapcenter-service.html["はじめに"]


